# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Measurement_Controller_0_1.ui'
#
# Created: Tue Sep 13 16:01:38 2016
#      by: PyQt4 UI code generator 4.9.6
#

import sys
import PyQt4
from PyQt4 import uic
from PyQt4.QtCore import *
from PyQt4.QtGui import *
import sys
import urllib2

import time
import threading

#from Tkinter import *

#import tkFont
import os
#import glob

import threading
import imageio
import Queue

import numpy as np

import pyvisa
import os, sys
sys.path.append('C:\python lab\qubit_setup\instruments')
sys.path.append('D:\Dropbox\MANIP\Code_for_Develop\Bat771_P9\Bat771_P9_Libraries')
sys.path.append('C:\python lab\libs\pyview\lib')
sys.path.append('C:\python lab\Bat771_P9\Bat771_P9_Libraries')

import itc1_oxford
import itc2_oxford
import yokogawa
import adlink9826

path1=os.path.realpath(__file__+'../../../')
import sys,os,os.path
from ctypes import *
import time
import threading

#itc1=itc1_oxford.Instr()
#itc2=itc2_oxford.Instr()

#itc1.initialize()
#itc2.initialize()

from PyQt4 import QtCore, QtGui
from matplotlibwidget import MatplotlibWidget

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


'''
import threading
import time


class Temp_itc_1(QtCore.QThread):
    Temps_sorb = QtCore.pyqtSignal(str)
    Temps_He3Low = QtCore.pyqtSignal(str)
    Temps_He3High = QtCore.pyqtSignal(str)
    Temps_HeatSW = QtCore.pyqtSignal(str)
    Temps_PT2 = QtCore.pyqtSignal(str)
    def __init__(self, parent=None):
        super(Temp_itc_1, self).__init__(parent)
    def run(self):
        itc1Temp_sorb = str(itc1.Temp_1())
        self.Temps_sorb.emit(itc1Temp_sorb)
        time.sleep(0.1)
        itc1Temp_He3Low = str(itc1.Temp_2())
        self.Temps_He3Low.emit(itc1Temp_He3Low)
        time.sleep(0.1)
        itc1Temp_He3High = str(itc1.Temp_3())
        self.Temps_He3High.emit(itc1Temp_He3High)
        time.sleep(0.1)
        itc2Temp_HeatSW = str(itc2.Temp_4())
        self.Temps_HeatSW.emit(itc2Temp_HeatSW)
        time.sleep(0.1)
        itc2Temp_PT2 = str(itc2.Temp_5())
        self.Temps_PT2.emit(itc2Temp_PT2)
'''
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1400, 1100)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mplwidget_fig_1=self.centralwidget
        #self.mplwidget_fig_1 = MatplotlibWidget(self.centralwidget)
        #self.mplwidget_fig_1.setGeometry(QtCore.QRect(50, 0, 1280, 650))
        #self.mplwidget_fig_1.setObjectName(_fromUtf8("mplwidget_fig_1"))

        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(980, 660, 341, 361))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))

        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(630, 660, 341, 361))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))


        self.label_Start = QtGui.QLabel(self.centralwidget)
        self.label_Start.setGeometry(QtCore.QRect(160, 670, 40, 25))
        self.label_Start.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Start.setObjectName(_fromUtf8("label_Start"))
        self.label_Stop = QtGui.QLabel(self.centralwidget)
        self.label_Stop.setGeometry(QtCore.QRect(230, 670, 40, 25))
        self.label_Stop.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stop.setObjectName(_fromUtf8("label_Stop"))

        self.radioButton_step = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_step.setGeometry(QtCore.QRect(287, 675, 82, 17))

        self.radioButton_step.setObjectName(_fromUtf8("radioButton_step"))

        self.buttonGroup_3 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.radioButton_step)

        self.label_Step = QtGui.QLabel(self.centralwidget)
        self.label_Step.setGeometry(QtCore.QRect(305, 670, 40, 25))
        self.label_Step.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Step.setObjectName(_fromUtf8("label_Step"))

        self.radioButton_datapoint = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_datapoint.setGeometry(QtCore.QRect(352, 675, 82, 17))
        self.radioButton_datapoint.setChecked(True)
        self.radioButton_datapoint.setObjectName(_fromUtf8("radioButton_datapoint"))
        self.buttonGroup_3.addButton(self.radioButton_datapoint)

        self.label_Datapoint = QtGui.QLabel(self.centralwidget)
        self.label_Datapoint.setGeometry(QtCore.QRect(370, 670, 40, 25))
        self.label_Datapoint.setObjectName(_fromUtf8("label_Datapoint"))

        self.label_repeat = QtGui.QLabel(self.centralwidget)
        self.label_repeat.setGeometry(QtCore.QRect(420, 670, 40, 25))
        self.label_repeat.setObjectName(_fromUtf8("label_repeat"))

        self.label_wait_time = QtGui.QLabel(self.centralwidget)
        self.label_wait_time.setGeometry(QtCore.QRect(470, 670, 40, 25))
        self.label_wait_time.setObjectName(_fromUtf8("label_repeat"))


        self.label_X_axis = QtGui.QLabel(self.centralwidget)
        self.label_X_axis.setGeometry(QtCore.QRect(10, 700, 40, 25))
        self.label_X_axis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X_axis.setObjectName(_fromUtf8("label_X_axis"))
        self.comboBox_x_axis = QtGui.QComboBox(self.centralwidget)
        self.comboBox_x_axis.setGeometry(QtCore.QRect(50, 700, 90, 25))
        self.comboBox_x_axis.setObjectName(_fromUtf8("comboBox_x_axis"))
        self.doubleSpinBox_x_start = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_x_start.setGeometry(QtCore.QRect(150, 700, 62, 25))
        self.doubleSpinBox_x_start.setDecimals(5)
        self.doubleSpinBox_x_start.setMinimum(-25.0)
        self.doubleSpinBox_x_start.setMaximum(25.0)
        self.doubleSpinBox_x_start.setSingleStep(1e-05)
        self.doubleSpinBox_x_start.setObjectName(_fromUtf8("doubleSpinBox_x_start"))
        self.doubleSpinBox_x_stop = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_x_stop.setGeometry(QtCore.QRect(220, 700, 62, 25))
        self.doubleSpinBox_x_stop.setDecimals(5)
        self.doubleSpinBox_x_stop.setMinimum(-25.0)
        self.doubleSpinBox_x_stop.setMaximum(25.0)
        self.doubleSpinBox_x_stop.setSingleStep(1e-05)
        self.doubleSpinBox_x_stop.setObjectName(_fromUtf8("doubleSpinBox_x_stop"))
        self.doubleSpinBox_x_step = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_x_step.setGeometry(QtCore.QRect(290, 700, 62, 25))
        self.doubleSpinBox_x_step.setDecimals(5)
        self.doubleSpinBox_x_step.setMinimum(-1.0)
        self.doubleSpinBox_x_step.setMaximum(1.0)
        self.doubleSpinBox_x_step.setSingleStep(1e-05)
        self.doubleSpinBox_x_step.setProperty("value", 0.001)
        self.doubleSpinBox_x_step.setObjectName(_fromUtf8("doubleSpinBox_x_step"))
        self.spinBox_x_datapoint = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_x_datapoint.setGeometry(QtCore.QRect(360, 700, 50, 25))
        self.spinBox_x_datapoint.setMinimum(1)
        self.spinBox_x_datapoint.setMaximum(100000)
        self.spinBox_x_datapoint.setProperty("value", 101)
        self.spinBox_x_datapoint.setObjectName(_fromUtf8("spinBox_x_datapoint"))
        self.spinBox_x_repeat = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_x_repeat.setGeometry(QtCore.QRect(420, 700, 40, 25))
        self.spinBox_x_repeat.setMinimum(1)
        self.spinBox_x_repeat.setMaximum(10000)
        self.spinBox_x_repeat.setObjectName(_fromUtf8("spinBox_x_repeat"))

        self.doubleSpinBox_x_wait_time = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_x_wait_time.setGeometry(QtCore.QRect(470, 700, 50, 25))
        self.doubleSpinBox_x_wait_time.setDecimals(1)
        self.doubleSpinBox_x_wait_time.setMinimum(0)
        self.doubleSpinBox_x_wait_time.setMaximum(999)
        self.doubleSpinBox_x_wait_time.setSingleStep(0.1)
        self.doubleSpinBox_x_wait_time.setProperty("value", 1.0)
        self.doubleSpinBox_x_wait_time.setObjectName(_fromUtf8("doubleSpinBox_x_wait_time"))


        self.label_Y_axis = QtGui.QLabel(self.centralwidget)
        self.label_Y_axis.setGeometry(QtCore.QRect(10, 730, 40, 25))
        self.label_Y_axis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y_axis.setObjectName(_fromUtf8("label_Y_axis"))
        self.comboBox_y_axis = QtGui.QComboBox(self.centralwidget)
        self.comboBox_y_axis.setGeometry(QtCore.QRect(50, 730, 90, 25))
        self.comboBox_y_axis.setObjectName(_fromUtf8("comboBox_y_axis"))
        self.doubleSpinBox_y_start = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_y_start.setGeometry(QtCore.QRect(150, 730, 62, 25))
        self.doubleSpinBox_y_start.setDecimals(5)
        self.doubleSpinBox_y_start.setMinimum(-25.0)
        self.doubleSpinBox_y_start.setMaximum(25.0)
        self.doubleSpinBox_y_start.setSingleStep(1e-05)
        self.doubleSpinBox_y_start.setObjectName(_fromUtf8("doubleSpinBox_y_start"))
        self.doubleSpinBox_y_stop = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_y_stop.setGeometry(QtCore.QRect(220, 730, 62, 25))
        self.doubleSpinBox_y_stop.setDecimals(5)
        self.doubleSpinBox_y_stop.setMinimum(-25.0)
        self.doubleSpinBox_y_stop.setMaximum(25.0)
        self.doubleSpinBox_y_stop.setSingleStep(1e-05)
        self.doubleSpinBox_y_stop.setObjectName(_fromUtf8("doubleSpinBox_y_stop"))
        self.doubleSpinBox_y_step = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_y_step.setGeometry(QtCore.QRect(290, 730, 62, 25))
        self.doubleSpinBox_y_step.setDecimals(4)
        self.doubleSpinBox_y_step.setMinimum(-1.0)
        self.doubleSpinBox_y_step.setMaximum(1.0)
        self.doubleSpinBox_y_step.setSingleStep(1e-05)
        self.doubleSpinBox_y_step.setProperty("value", 0.001)
        self.doubleSpinBox_y_step.setObjectName(_fromUtf8("doubleSpinBox_y_step"))
        self.spinBox_y_datapoint = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_y_datapoint.setGeometry(QtCore.QRect(360, 730, 50, 25))
        self.spinBox_y_datapoint.setMinimum(1)
        self.spinBox_y_datapoint.setMaximum(100000)
        self.spinBox_y_datapoint.setObjectName(_fromUtf8("spinBox_y_datapoint"))
        self.spinBox_y_repeat = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_y_repeat.setGeometry(QtCore.QRect(420, 730, 40, 25))
        self.spinBox_y_repeat.setMinimum(1)
        self.spinBox_y_repeat.setMaximum(10000)
        self.spinBox_y_repeat.setObjectName(_fromUtf8("spinBox_y_repeat"))

        self.doubleSpinBox_y_wait_time = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_y_wait_time.setGeometry(QtCore.QRect(470, 730, 50, 25))
        self.doubleSpinBox_y_wait_time.setDecimals(1)
        self.doubleSpinBox_y_wait_time.setMinimum(0)
        self.doubleSpinBox_y_wait_time.setMaximum(999)
        self.doubleSpinBox_y_wait_time.setSingleStep(0.1)
        self.doubleSpinBox_y_wait_time.setProperty("value", 1.0)
        self.doubleSpinBox_y_wait_time.setObjectName(_fromUtf8("doubleSpinBox_y_wait_time"))

        self.label_Z_axis = QtGui.QLabel(self.centralwidget)
        self.label_Z_axis.setGeometry(QtCore.QRect(10, 760, 40, 25))
        self.label_Z_axis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z_axis.setObjectName(_fromUtf8("label_Z_axis"))
        self.comboBox_z_axis = QtGui.QComboBox(self.centralwidget)
        self.comboBox_z_axis.setGeometry(QtCore.QRect(50, 760, 90, 25))
        self.comboBox_z_axis.setObjectName(_fromUtf8("comboBox_z_axis"))
        self.doubleSpinBox_z_start = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_z_start.setGeometry(QtCore.QRect(150, 760, 62, 25))
        self.doubleSpinBox_z_start.setDecimals(5)
        self.doubleSpinBox_z_start.setMinimum(-25.0)
        self.doubleSpinBox_z_start.setMaximum(25.0)
        self.doubleSpinBox_z_start.setSingleStep(1e-05)
        self.doubleSpinBox_z_start.setObjectName(_fromUtf8("doubleSpinBox_z_start"))
        self.doubleSpinBox_z_stop = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_z_stop.setGeometry(QtCore.QRect(220, 760, 62, 25))
        self.doubleSpinBox_z_stop.setDecimals(5)
        self.doubleSpinBox_z_stop.setMinimum(-25.0)
        self.doubleSpinBox_z_stop.setMaximum(25.0)
        self.doubleSpinBox_z_stop.setSingleStep(1e-05)
        self.doubleSpinBox_z_stop.setObjectName(_fromUtf8("doubleSpinBox_z_stop"))
        self.doubleSpinBox_z_step = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_z_step.setGeometry(QtCore.QRect(290, 760, 62, 25))
        self.doubleSpinBox_z_step.setDecimals(4)
        self.doubleSpinBox_z_step.setMinimum(-1.0)
        self.doubleSpinBox_z_step.setMaximum(1.0)
        self.doubleSpinBox_z_step.setSingleStep(1e-05)
        self.doubleSpinBox_z_step.setProperty("value", 0.001)
        self.doubleSpinBox_z_step.setObjectName(_fromUtf8("doubleSpinBox_z_step"))
        self.spinBox_z_datapoint = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_z_datapoint.setGeometry(QtCore.QRect(360, 760, 50, 25))
        self.spinBox_z_datapoint.setMinimum(1)
        self.spinBox_z_datapoint.setMaximum(100000)
        self.spinBox_z_datapoint.setObjectName(_fromUtf8("spinBox_z_datapoint"))
        self.spinBox_z_repeat = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_z_repeat.setGeometry(QtCore.QRect(420, 760, 40, 25))
        self.spinBox_z_repeat.setMinimum(1)
        self.spinBox_z_repeat.setMaximum(10000)
        self.spinBox_z_repeat.setObjectName(_fromUtf8("spinBox_z_repeat"))
        self.doubleSpinBox_z_wait_time = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_z_wait_time.setGeometry(QtCore.QRect(470, 760, 50, 25))
        self.doubleSpinBox_z_wait_time.setDecimals(1)
        self.doubleSpinBox_z_wait_time.setMinimum(0)
        self.doubleSpinBox_z_wait_time.setMaximum(999)
        self.doubleSpinBox_z_wait_time.setSingleStep(0.1)
        self.doubleSpinBox_z_wait_time.setProperty("value", 1.0)
        self.doubleSpinBox_z_wait_time.setObjectName(_fromUtf8("doubleSpinBox_z_wait_time"))

        self.label_r_axis = QtGui.QLabel(self.centralwidget)
        self.label_r_axis.setGeometry(QtCore.QRect(10, 790, 40, 25))
        self.label_r_axis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r_axis.setObjectName(_fromUtf8("label_r_axis"))
        self.comboBox_r_axis = QtGui.QComboBox(self.centralwidget)
        self.comboBox_r_axis.setGeometry(QtCore.QRect(50, 790, 90, 25))
        self.comboBox_r_axis.setObjectName(_fromUtf8("comboBox_r_axis"))
        self.doubleSpinBox_r_start = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_r_start.setGeometry(QtCore.QRect(150, 790, 62, 25))
        self.doubleSpinBox_r_start.setDecimals(5)
        self.doubleSpinBox_r_start.setMinimum(-25.0)
        self.doubleSpinBox_r_start.setMaximum(25.0)
        self.doubleSpinBox_r_start.setSingleStep(1e-05)
        self.doubleSpinBox_r_start.setObjectName(_fromUtf8("doubleSpinBox_r_start"))
        self.doubleSpinBox_r_stop = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_r_stop.setGeometry(QtCore.QRect(220, 790, 62, 25))
        self.doubleSpinBox_r_stop.setDecimals(5)
        self.doubleSpinBox_r_stop.setMinimum(-25.0)
        self.doubleSpinBox_r_stop.setMaximum(25.0)
        self.doubleSpinBox_r_stop.setSingleStep(1e-05)
        self.doubleSpinBox_r_stop.setObjectName(_fromUtf8("doubleSpinBox_r_stop"))
        self.doubleSpinBox_r_step = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_r_step.setGeometry(QtCore.QRect(290, 790, 62, 25))
        self.doubleSpinBox_r_step.setDecimals(4)
        self.doubleSpinBox_r_step.setMinimum(-1.0)
        self.doubleSpinBox_r_step.setMaximum(1.0)
        self.doubleSpinBox_r_step.setSingleStep(1e-05)
        self.doubleSpinBox_r_step.setProperty("value", 0.001)
        self.doubleSpinBox_r_step.setObjectName(_fromUtf8("doubleSpinBox_r_step"))
        self.spinBox_r_datapoint = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_r_datapoint.setGeometry(QtCore.QRect(360, 790, 50, 25))
        self.spinBox_r_datapoint.setMinimum(1)
        self.spinBox_r_datapoint.setMaximum(100000)
        self.spinBox_r_datapoint.setObjectName(_fromUtf8("spinBox_r_datapoint"))
        self.spinBox_r_repeat = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_r_repeat.setGeometry(QtCore.QRect(420, 790, 40, 25))
        self.spinBox_r_repeat.setMinimum(1)
        self.spinBox_r_repeat.setMaximum(10000)
        self.spinBox_r_repeat.setObjectName(_fromUtf8("spinBox_r_repeat"))
        self.doubleSpinBox_r_wait_time = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_r_wait_time.setGeometry(QtCore.QRect(470, 790, 50, 25))
        self.doubleSpinBox_r_wait_time.setDecimals(1)
        self.doubleSpinBox_r_wait_time.setMinimum(0)
        self.doubleSpinBox_r_wait_time.setMaximum(999)
        self.doubleSpinBox_r_wait_time.setSingleStep(0.1)
        self.doubleSpinBox_r_wait_time.setProperty("value", 1.0)
        self.doubleSpinBox_r_wait_time.setObjectName(_fromUtf8("doubleSpinBox_r_wait_time"))

        self.label_Measure_lockin = QtGui.QLabel(self.centralwidget)
        self.label_Measure_lockin.setGeometry(QtCore.QRect(10, 1020, 40, 25))
        self.label_Measure_lockin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Measure_lockin.setObjectName(_fromUtf8("label_Measure_lockin"))

        self.checkBox_Measure_lockin = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_Measure_lockin.setGeometry(QtCore.QRect(50, 1020, 40, 25))
        self.checkBox_Measure_lockin.setText(_fromUtf8(""))
        self.checkBox_Measure_lockin.setChecked(True)
        self.checkBox_Measure_lockin.setAutoRepeat(True)
        self.checkBox_Measure_lockin.setObjectName(_fromUtf8("checkBox_Measure_lockin"))

        self.label_Measure_Noise = QtGui.QLabel(self.centralwidget)
        self.label_Measure_Noise.setGeometry(QtCore.QRect(10, 1040, 40, 25))
        self.label_Measure_Noise.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Measure_Noise.setObjectName(_fromUtf8("label_Measure_Noise"))

        self.checkBox_Measure_Noise = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_Measure_Noise.setGeometry(QtCore.QRect(50, 1040, 40, 25))
        self.checkBox_Measure_Noise.setText(_fromUtf8(""))
        self.checkBox_Measure_Noise.setChecked(True)
        self.checkBox_Measure_Noise.setAutoRepeat(True)
        self.checkBox_Measure_Noise.setObjectName(_fromUtf8("checkBox_Measure_Noise"))


        self.pushButton_run = QtGui.QPushButton(self.centralwidget)
        self.pushButton_run.setGeometry(QtCore.QRect(40, 960, 75, 23))
        self.pushButton_run.setObjectName(_fromUtf8("pushButton_run"))
        self.pushButton_pause = QtGui.QPushButton(self.centralwidget)
        self.pushButton_pause.setGeometry(QtCore.QRect(120, 960, 75, 23))
        self.pushButton_pause.setObjectName(_fromUtf8("pushButton_pause"))
        self.pushButton_stop = QtGui.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(200, 960, 75, 23))
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 990, 230, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))


        self.tab_Figure_Setup = QtGui.QWidget()
        self.tab_Figure_Setup.setObjectName(_fromUtf8("tab_Figure_Setup"))
        self.tabWidget_2.addTab(self.tab_Figure_Setup, _fromUtf8(""))

        self.checkBox_subfig_1 = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_1.setGeometry(QtCore.QRect(5, 30, 15, 25))
        self.checkBox_subfig_1.setText(_fromUtf8(""))
        self.checkBox_subfig_1.setChecked(False)
        self.checkBox_subfig_1.setAutoRepeat(True)
        self.checkBox_subfig_1.setObjectName(_fromUtf8("checkBox_subfig_1"))

        self.comboBox_subfig_1 = QtGui.QComboBox(self.tab_Figure_Setup)
        self.comboBox_subfig_1.setGeometry(QtCore.QRect(20, 30, 65, 25))
        self.comboBox_subfig_1.setObjectName(_fromUtf8("comboBox_subfig_1"))

        self.checkBox_subfig_1_img_type = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_1_img_type.setGeometry(QtCore.QRect(100, 30, 15, 25))
        self.checkBox_subfig_1_img_type.setText(_fromUtf8(""))
        self.checkBox_subfig_1_img_type.setChecked(False)
        self.checkBox_subfig_1_img_type.setAutoRepeat(True)
        self.checkBox_subfig_1_img_type.setObjectName(_fromUtf8("checkBox_subfig_1_img_type"))

        self.checkBox_subfig_2 = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_2.setGeometry(QtCore.QRect(115, 30, 15, 25))
        self.checkBox_subfig_2.setText(_fromUtf8(""))
        self.checkBox_subfig_2.setChecked(False)
        self.checkBox_subfig_2.setAutoRepeat(True)
        self.checkBox_subfig_2.setObjectName(_fromUtf8("checkBox_subfig_2"))

        self.comboBox_subfig_2 = QtGui.QComboBox(self.tab_Figure_Setup)
        self.comboBox_subfig_2.setGeometry(QtCore.QRect(130, 30, 65, 25))
        self.comboBox_subfig_2.setObjectName(_fromUtf8("comboBox_subfig_2"))

        self.checkBox_subfig_2_img_type = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_2_img_type.setGeometry(QtCore.QRect(210, 30, 15, 25))
        self.checkBox_subfig_2_img_type.setText(_fromUtf8(""))
        self.checkBox_subfig_2_img_type.setChecked(False)
        self.checkBox_subfig_2_img_type.setAutoRepeat(True)
        self.checkBox_subfig_2_img_type.setObjectName(_fromUtf8("checkBox_subfig_2_img_type"))

        self.checkBox_subfig_3 = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_3.setGeometry(QtCore.QRect(225, 30, 15, 25))
        self.checkBox_subfig_3.setText(_fromUtf8(""))
        self.checkBox_subfig_3.setChecked(False)
        self.checkBox_subfig_3.setAutoRepeat(True)
        self.checkBox_subfig_3.setObjectName(_fromUtf8("checkBox_subfig_3"))
        self.comboBox_subfig_3 = QtGui.QComboBox(self.tab_Figure_Setup)
        self.comboBox_subfig_3.setGeometry(QtCore.QRect(240, 30, 85, 25))
        self.comboBox_subfig_3.setObjectName(_fromUtf8("comboBox_subfig_3"))

        self.checkBox_subfig_3_img_type = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_3_img_type.setGeometry(QtCore.QRect(320, 30, 15, 25))
        self.checkBox_subfig_3_img_type.setText(_fromUtf8(""))
        self.checkBox_subfig_3_img_type.setChecked(False)
        self.checkBox_subfig_3_img_type.setAutoRepeat(True)
        self.checkBox_subfig_3_img_type.setObjectName(_fromUtf8("checkBox_subfig_3_img_type"))

        self.checkBox_subfig_4 = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_4.setGeometry(QtCore.QRect(5, 110, 15, 25))
        self.checkBox_subfig_4.setText(_fromUtf8(""))
        self.checkBox_subfig_4.setChecked(False)
        self.checkBox_subfig_4.setAutoRepeat(True)
        self.checkBox_subfig_4.setObjectName(_fromUtf8("checkBox_subfig_4"))
        self.comboBox_subfig_4 = QtGui.QComboBox(self.tab_Figure_Setup)
        self.comboBox_subfig_4.setGeometry(QtCore.QRect(20, 110, 85, 25))
        self.comboBox_subfig_4.setObjectName(_fromUtf8("comboBox_subfig_4"))

        self.checkBox_subfig_4_img_type = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_4_img_type.setGeometry(QtCore.QRect(100, 110, 15, 25))
        self.checkBox_subfig_4_img_type.setText(_fromUtf8(""))
        self.checkBox_subfig_4_img_type.setChecked(False)
        self.checkBox_subfig_4_img_type.setAutoRepeat(True)
        self.checkBox_subfig_4_img_type.setObjectName(_fromUtf8("checkBox_subfig_4_img_type"))

        self.checkBox_subfig_5 = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_5.setGeometry(QtCore.QRect(115, 110, 15, 25))
        self.checkBox_subfig_5.setText(_fromUtf8(""))
        self.checkBox_subfig_5.setChecked(False)
        self.checkBox_subfig_5.setAutoRepeat(True)
        self.checkBox_subfig_5.setObjectName(_fromUtf8("checkBox_subfig_5"))
        self.comboBox_subfig_5 = QtGui.QComboBox(self.tab_Figure_Setup)
        self.comboBox_subfig_5.setGeometry(QtCore.QRect(130, 110, 85, 25))
        self.comboBox_subfig_5.setObjectName(_fromUtf8("comboBox_subfig_5"))

        self.checkBox_subfig_5_img_type = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_5_img_type.setGeometry(QtCore.QRect(210, 110, 15, 25))
        self.checkBox_subfig_5_img_type.setText(_fromUtf8(""))
        self.checkBox_subfig_5_img_type.setChecked(False)
        self.checkBox_subfig_5_img_type.setAutoRepeat(True)
        self.checkBox_subfig_5_img_type.setObjectName(_fromUtf8("checkBox_subfig_5_img_type"))

        self.checkBox_subfig_6 = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_6.setGeometry(QtCore.QRect(225, 110, 15, 25))
        self.checkBox_subfig_6.setText(_fromUtf8(""))
        self.checkBox_subfig_6.setChecked(False)
        self.checkBox_subfig_6.setAutoRepeat(True)
        self.checkBox_subfig_6.setObjectName(_fromUtf8("checkBox_subfig_6"))
        self.comboBox_subfig_6 = QtGui.QComboBox(self.tab_Figure_Setup)
        self.comboBox_subfig_6.setGeometry(QtCore.QRect(240, 110, 85, 25))
        self.comboBox_subfig_6.setObjectName(_fromUtf8("comboBox_subfig_6"))

        self.checkBox_subfig_6_img_type = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_6_img_type.setGeometry(QtCore.QRect(320, 110, 15, 25))
        self.checkBox_subfig_6_img_type.setText(_fromUtf8(""))
        self.checkBox_subfig_6_img_type.setChecked(False)
        self.checkBox_subfig_6_img_type.setAutoRepeat(True)
        self.checkBox_subfig_6_img_type.setObjectName(_fromUtf8("checkBox_subfig_6_img_type"))

        self.checkBox_subfig_7 = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_7.setGeometry(QtCore.QRect(5, 190, 15, 25))
        self.checkBox_subfig_7.setText(_fromUtf8(""))
        self.checkBox_subfig_7.setChecked(False)
        self.checkBox_subfig_7.setAutoRepeat(True)
        self.checkBox_subfig_7.setObjectName(_fromUtf8("checkBox_subfig_7"))
        self.comboBox_subfig_7 = QtGui.QComboBox(self.tab_Figure_Setup)
        self.comboBox_subfig_7.setGeometry(QtCore.QRect(20, 190, 85, 25))
        self.comboBox_subfig_7.setObjectName(_fromUtf8("comboBox_subfig_7"))

        self.checkBox_subfig_7_img_type = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_7_img_type.setGeometry(QtCore.QRect(100, 190, 15, 25))
        self.checkBox_subfig_7_img_type.setText(_fromUtf8(""))
        self.checkBox_subfig_7_img_type.setChecked(False)
        self.checkBox_subfig_7_img_type.setAutoRepeat(True)
        self.checkBox_subfig_7_img_type.setObjectName(_fromUtf8("checkBox_subfig_7_img_type"))

        self.checkBox_subfig_8 = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_8.setGeometry(QtCore.QRect(115, 190, 15, 25))
        self.checkBox_subfig_8.setText(_fromUtf8(""))
        self.checkBox_subfig_8.setChecked(False)
        self.checkBox_subfig_8.setAutoRepeat(True)
        self.checkBox_subfig_8.setObjectName(_fromUtf8("checkBox_subfig_8"))
        self.comboBox_subfig_8 = QtGui.QComboBox(self.tab_Figure_Setup)
        self.comboBox_subfig_8.setGeometry(QtCore.QRect(130, 190, 85, 25))
        self.comboBox_subfig_8.setObjectName(_fromUtf8("comboBox_subfig_8"))

        self.checkBox_subfig_8_img_type = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_8_img_type.setGeometry(QtCore.QRect(210, 190, 15, 25))
        self.checkBox_subfig_8_img_type.setText(_fromUtf8(""))
        self.checkBox_subfig_8_img_type.setChecked(False)
        self.checkBox_subfig_8_img_type.setAutoRepeat(True)
        self.checkBox_subfig_8_img_type.setObjectName(_fromUtf8("checkBox_subfig_8_img_type"))

        self.checkBox_subfig_9 = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_9.setGeometry(QtCore.QRect(225, 190, 15, 25))
        self.checkBox_subfig_9.setText(_fromUtf8(""))
        self.checkBox_subfig_9.setChecked(False)
        self.checkBox_subfig_9.setAutoRepeat(True)
        self.checkBox_subfig_9.setObjectName(_fromUtf8("checkBox_subfig_9"))
        self.comboBox_subfig_9 = QtGui.QComboBox(self.tab_Figure_Setup)
        self.comboBox_subfig_9.setGeometry(QtCore.QRect(240, 190, 85, 25))
        self.comboBox_subfig_9.setObjectName(_fromUtf8("comboBox_subfig_9"))

        self.checkBox_subfig_9_img_type = QtGui.QCheckBox(self.tab_Figure_Setup)
        self.checkBox_subfig_9_img_type.setGeometry(QtCore.QRect(320, 190, 15, 25))
        self.checkBox_subfig_9_img_type.setText(_fromUtf8(""))
        self.checkBox_subfig_9_img_type.setChecked(False)
        self.checkBox_subfig_9_img_type.setAutoRepeat(True)
        self.checkBox_subfig_9_img_type.setObjectName(_fromUtf8("checkBox_subfig_9_img_type"))

        self.radioButton_preset_1 = QtGui.QRadioButton(self.tab_Figure_Setup)
        self.radioButton_preset_1.setGeometry(QtCore.QRect(30, 280, 82, 17))
        self.radioButton_preset_1.setChecked(True)
        self.radioButton_preset_1.setObjectName(_fromUtf8("radioButton_preset_1"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButton_preset_1)
        self.radioButton_2 = QtGui.QRadioButton(self.tab_Figure_Setup)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 300, 82, 17))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup_2.addButton(self.radioButton_2)

        self.tab_Parameters_2 = QtGui.QWidget()
        self.tab_Parameters_2.setObjectName(_fromUtf8("tab_Parameters_2"))
        self.tabWidget_2.addTab(self.tab_Parameters_2, _fromUtf8(""))

        self.checkBox_ADLINK_save = QtGui.QCheckBox(self.tab_Parameters_2)
        self.checkBox_ADLINK_save.setGeometry(QtCore.QRect(305, 25, 15, 20))
        self.checkBox_ADLINK_save.setText(_fromUtf8(""))
        self.checkBox_ADLINK_save.setChecked(False)
        self.checkBox_ADLINK_save.setAutoRepeat(False)
        self.checkBox_ADLINK_save.setObjectName(_fromUtf8("checkBox_ADLINK_save"))
        self.label_ADLINK_save = QtGui.QLabel(self.tab_Parameters_2)
        self.label_ADLINK_save.setGeometry(QtCore.QRect(290, 5, 40, 20))
        self.label_ADLINK_save.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ADLINK_save.setObjectName(_fromUtf8("label_ADLINK_save"))
        self.label_ADLINK_avgnum = QtGui.QLabel(self.tab_Parameters_2)
        self.label_ADLINK_avgnum.setGeometry(QtCore.QRect(230, 5, 40, 20))
        self.label_ADLINK_avgnum.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ADLINK_avgnum.setObjectName(_fromUtf8("label_ADLINK_avgnum"))
        self.label_ADLINK_9826 = QtGui.QLabel(self.tab_Parameters_2)
        self.label_ADLINK_9826.setGeometry(QtCore.QRect(5, 25, 71, 25))
        self.label_ADLINK_9826.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ADLINK_9826.setObjectName(_fromUtf8("label_ADLINK_9826"))
        self.label_Stop_2 = QtGui.QLabel(self.tab_Parameters_2)
        self.label_Stop_2.setGeometry(QtCore.QRect(160, 5, 40, 20))
        self.label_Stop_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Stop_2.setObjectName(_fromUtf8("label_Stop_2"))
        self.doubleSpinBox_ADLINK_start = QtGui.QDoubleSpinBox(self.tab_Parameters_2)
        self.doubleSpinBox_ADLINK_start.setGeometry(QtCore.QRect(80, 25, 62, 25))
        self.doubleSpinBox_ADLINK_start.setDecimals(0)
        self.doubleSpinBox_ADLINK_start.setMinimum(0.0)
        self.doubleSpinBox_ADLINK_start.setMaximum(100000.0)
        self.doubleSpinBox_ADLINK_start.setSingleStep(1.0)
        self.doubleSpinBox_ADLINK_start.setProperty("value", 20000.0)
        self.doubleSpinBox_ADLINK_start.setObjectName(_fromUtf8("doubleSpinBox_ADLINK_start"))
        self.doubleSpinBox_ADLINK_stop = QtGui.QDoubleSpinBox(self.tab_Parameters_2)
        self.doubleSpinBox_ADLINK_stop.setGeometry(QtCore.QRect(150, 25, 62, 25))
        self.doubleSpinBox_ADLINK_stop.setDecimals(0)
        self.doubleSpinBox_ADLINK_stop.setMinimum(0.0)
        self.doubleSpinBox_ADLINK_stop.setMaximum(100000.0)
        self.doubleSpinBox_ADLINK_stop.setSingleStep(1.0)
        self.doubleSpinBox_ADLINK_stop.setProperty("value", 60000.0)
        self.doubleSpinBox_ADLINK_stop.setObjectName(_fromUtf8("doubleSpinBox_ADLINK_stop"))
        self.label_Start_2 = QtGui.QLabel(self.tab_Parameters_2)
        self.label_Start_2.setGeometry(QtCore.QRect(90, 5, 40, 20))
        self.label_Start_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Start_2.setObjectName(_fromUtf8("label_Start_2"))
        self.doubleSpinBox_ADLINK_avgnum = QtGui.QDoubleSpinBox(self.tab_Parameters_2)
        self.doubleSpinBox_ADLINK_avgnum.setGeometry(QtCore.QRect(220, 25, 62, 25))
        self.doubleSpinBox_ADLINK_avgnum.setDecimals(0)
        self.doubleSpinBox_ADLINK_avgnum.setMinimum(0.0)
        self.doubleSpinBox_ADLINK_avgnum.setMaximum(100000.0)
        self.doubleSpinBox_ADLINK_avgnum.setSingleStep(1.0)
        self.doubleSpinBox_ADLINK_avgnum.setProperty("value", 1000.0)
        self.doubleSpinBox_ADLINK_avgnum.setObjectName(_fromUtf8("doubleSpinBox_ADLINK_avgnum"))
        self.label_Volt_of_Amp_A = QtGui.QLabel(self.tab_Parameters_2)
        self.label_Volt_of_Amp_A.setGeometry(QtCore.QRect(5, 55, 71, 25))
        self.label_Volt_of_Amp_A.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Volt_of_Amp_A.setObjectName(_fromUtf8("label_Volt_of_Amp_A"))
        self.doubleSpinBox_Volt_of_Amp_A = QtGui.QDoubleSpinBox(self.tab_Parameters_2)
        self.doubleSpinBox_Volt_of_Amp_A.setGeometry(QtCore.QRect(80, 55, 62, 25))
        self.doubleSpinBox_Volt_of_Amp_A.setDecimals(3)
        self.doubleSpinBox_Volt_of_Amp_A.setMinimum(0.0)
        self.doubleSpinBox_Volt_of_Amp_A.setMaximum(25.0)
        self.doubleSpinBox_Volt_of_Amp_A.setSingleStep(0.001)
        self.doubleSpinBox_Volt_of_Amp_A.setProperty("value", 0.0)
        self.doubleSpinBox_Volt_of_Amp_A.setObjectName(_fromUtf8("doubleSpinBox_Volt_of_Amp_A"))
        self.doubleSpinBox_Volt_of_Amp_B = QtGui.QDoubleSpinBox(self.tab_Parameters_2)
        self.doubleSpinBox_Volt_of_Amp_B.setGeometry(QtCore.QRect(220, 55, 62, 25))
        self.doubleSpinBox_Volt_of_Amp_B.setDecimals(3)
        self.doubleSpinBox_Volt_of_Amp_B.setMinimum(0.0)
        self.doubleSpinBox_Volt_of_Amp_B.setMaximum(25.0)
        self.doubleSpinBox_Volt_of_Amp_B.setSingleStep(0.001)
        self.doubleSpinBox_Volt_of_Amp_B.setProperty("value", 0.0)
        self.doubleSpinBox_Volt_of_Amp_B.setObjectName(_fromUtf8("doubleSpinBox_Volt_of_Amp_B"))
        self.label_Volt_of_Amp_B = QtGui.QLabel(self.tab_Parameters_2)
        self.label_Volt_of_Amp_B.setGeometry(QtCore.QRect(145, 55, 71, 25))
        self.label_Volt_of_Amp_B.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Volt_of_Amp_B.setObjectName(_fromUtf8("label_Volt_of_Amp_B"))
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.tab_Parameters_2)
        self.dateTimeEdit.setGeometry(QtCore.QRect(80, 85, 200, 25))
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 9, 13), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.label_Volt_of_Amp_A_2 = QtGui.QLabel(self.tab_Parameters_2)
        self.label_Volt_of_Amp_A_2.setGeometry(QtCore.QRect(5, 85, 71, 25))
        self.label_Volt_of_Amp_A_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Volt_of_Amp_A_2.setObjectName(_fromUtf8("label_Volt_of_Amp_A_2"))


        self.tab_ITC_Control = QtGui.QWidget()
        self.tab_ITC_Control.setObjectName(_fromUtf8("tab_ITC_Control"))
        self.tabWidget.addTab(self.tab_ITC_Control, _fromUtf8(""))

        self.label_ITC_Sorb = QtGui.QLabel(self.tab_ITC_Control)
        self.label_ITC_Sorb.setGeometry(QtCore.QRect(150, 20, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ITC_Sorb.setFont(font)
        self.label_ITC_Sorb.setObjectName(_fromUtf8("label_ITC_Sorb"))
        self.lcdNumber_ITC_Sorb = QtGui.QLCDNumber(self.tab_ITC_Control)
        self.lcdNumber_ITC_Sorb.setGeometry(QtCore.QRect(210, 10, 110, 40))
        self.lcdNumber_ITC_Sorb.setSmallDecimalPoint(True)
        self.lcdNumber_ITC_Sorb.setNumDigits(4)
        self.lcdNumber_ITC_Sorb.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_ITC_Sorb.setProperty("intValue", 0)
        self.lcdNumber_ITC_Sorb.setObjectName(_fromUtf8("lcdNumber_ITC_Sorb"))

        self.label_ITC_He3Low = QtGui.QLabel(self.tab_ITC_Control)
        self.label_ITC_He3Low.setGeometry(QtCore.QRect(150, 60, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ITC_He3Low.setFont(font)
        self.label_ITC_He3Low.setObjectName(_fromUtf8("label_ITC_He3Low"))
        self.lcdNumber_ITC_He3Low = QtGui.QLCDNumber(self.tab_ITC_Control)
        self.lcdNumber_ITC_He3Low.setGeometry(QtCore.QRect(210, 50, 110, 40))
        self.lcdNumber_ITC_He3Low.setSmallDecimalPoint(True)
        self.lcdNumber_ITC_He3Low.setNumDigits(4)
        self.lcdNumber_ITC_He3Low.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_ITC_He3Low.setProperty("intValue", 0)
        self.lcdNumber_ITC_He3Low.setObjectName(_fromUtf8("lcdNumber_ITC_He3Low"))

        self.label_He3High = QtGui.QLabel(self.tab_ITC_Control)
        self.label_He3High.setGeometry(QtCore.QRect(150, 100, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_He3High.setFont(font)
        self.label_He3High.setObjectName(_fromUtf8("label_He3High"))
        self.lcdNumber_ITC_He3High = QtGui.QLCDNumber(self.tab_ITC_Control)
        self.lcdNumber_ITC_He3High.setGeometry(QtCore.QRect(210, 90, 110, 40))
        self.lcdNumber_ITC_He3High.setSmallDecimalPoint(True)
        self.lcdNumber_ITC_He3High.setNumDigits(4)
        self.lcdNumber_ITC_He3High.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_ITC_He3High.setProperty("intValue", 0)
        self.lcdNumber_ITC_He3High.setObjectName(_fromUtf8("lcdNumber_ITC_He3High"))

        self.label_HeatSW = QtGui.QLabel(self.tab_ITC_Control)
        self.label_HeatSW.setGeometry(QtCore.QRect(150, 140, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_HeatSW.setFont(font)
        self.label_HeatSW.setObjectName(_fromUtf8("label_HeatSW"))
        self.lcdNumber_ITC_HeatSW = QtGui.QLCDNumber(self.tab_ITC_Control)
        self.lcdNumber_ITC_HeatSW.setGeometry(QtCore.QRect(210, 130, 110, 40))
        self.lcdNumber_ITC_HeatSW.setSmallDecimalPoint(True)
        self.lcdNumber_ITC_HeatSW.setNumDigits(4)
        self.lcdNumber_ITC_HeatSW.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_ITC_HeatSW.setProperty("intValue", 0)
        self.lcdNumber_ITC_HeatSW.setObjectName(_fromUtf8("lcdNumber_ITC_HeatSW"))

        self.label_PT2 = QtGui.QLabel(self.tab_ITC_Control)
        self.label_PT2.setGeometry(QtCore.QRect(150, 180, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_PT2.setFont(font)
        self.label_PT2.setObjectName(_fromUtf8("label_PT2"))
        self.lcdNumber_ITC_PT2 = QtGui.QLCDNumber(self.tab_ITC_Control)
        self.lcdNumber_ITC_PT2.setGeometry(QtCore.QRect(210, 170, 110, 40))
        self.lcdNumber_ITC_PT2.setSmallDecimalPoint(True)
        self.lcdNumber_ITC_PT2.setNumDigits(4)
        self.lcdNumber_ITC_PT2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_ITC_PT2.setProperty("intValue", 0)
        self.lcdNumber_ITC_PT2.setObjectName(_fromUtf8("lcdNumber_ITC_PT2"))

        self.label_Gauge_sorb_ITC = QtGui.QLabel(self.tab_ITC_Control)
        self.label_Gauge_sorb_ITC.setGeometry(QtCore.QRect(150, 220, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Gauge_sorb_ITC.setFont(font)
        self.label_Gauge_sorb_ITC.setObjectName(_fromUtf8("label_Gauge_sorb_ITC"))
        self.Gauge_sorb_power_ITC = QtGui.QProgressBar(self.tab_ITC_Control)
        self.Gauge_sorb_power_ITC.setGeometry(QtCore.QRect(210, 220, 120, 20))
        self.Gauge_sorb_power_ITC.setMaximum(99)
        self.Gauge_sorb_power_ITC.setProperty("value", 0)
        self.Gauge_sorb_power_ITC.setObjectName(_fromUtf8("Gauge_sorb_power_ITC"))

        self.label_Gauge_Heatsw_ITC = QtGui.QLabel(self.tab_ITC_Control)
        self.label_Gauge_Heatsw_ITC.setGeometry(QtCore.QRect(150, 250, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Gauge_Heatsw_ITC.setFont(font)
        self.label_Gauge_Heatsw_ITC.setObjectName(_fromUtf8("label_Gauge_Heatsw_ITC"))
        self.Gauge_Heat_power_ITC = QtGui.QProgressBar(self.tab_ITC_Control)
        self.Gauge_Heat_power_ITC.setGeometry(QtCore.QRect(210, 250, 120, 20))
        self.Gauge_Heat_power_ITC.setMaximum(99)
        self.Gauge_Heat_power_ITC.setProperty("value", 0)
        self.Gauge_Heat_power_ITC.setObjectName(_fromUtf8("Gauge_Heat_power_ITC"))

        self.Lamp_Recon_On_ITC = QtGui.QProgressBar(self.tab_ITC_Control)
        self.Lamp_Recon_On_ITC.setGeometry(QtCore.QRect(10, 20, 21, 23))
        self.Lamp_Recon_On_ITC.setMaximum(1)
        self.Lamp_Recon_On_ITC.setProperty("value", 0)
        self.Lamp_Recon_On_ITC.setAlignment(QtCore.Qt.AlignCenter)
        self.Lamp_Recon_On_ITC.setTextVisible(False)
        self.Lamp_Recon_On_ITC.setFormat(_fromUtf8(""))
        self.Lamp_Recon_On_ITC.setObjectName(_fromUtf8("Lamp_Recon_On_ITC"))
        self.pushButton_Recon_On_ITC = QtGui.QPushButton(self.tab_ITC_Control)
        self.pushButton_Recon_On_ITC.setGeometry(QtCore.QRect(40, 20, 70, 25))
        self.pushButton_Recon_On_ITC.setObjectName(_fromUtf8("pushButton_Recon_On_ITC"))

        self.Lamp_Heat_sw_on = QtGui.QProgressBar(self.tab_ITC_Control)
        self.Lamp_Heat_sw_on.setGeometry(QtCore.QRect(10, 200, 21, 23))
        self.Lamp_Heat_sw_on.setMaximum(100)
        self.Lamp_Heat_sw_on.setProperty("value", 0)
        self.Lamp_Heat_sw_on.setAlignment(QtCore.Qt.AlignCenter)
        self.Lamp_Heat_sw_on.setTextVisible(False)
        self.Lamp_Heat_sw_on.setFormat(_fromUtf8(""))
        self.Lamp_Heat_sw_on.setObjectName(_fromUtf8("Lamp_Heat_sw_On"))
        self.pushButton_Heat_SW = QtGui.QPushButton(self.tab_ITC_Control)
        self.pushButton_Heat_SW.setGeometry(QtCore.QRect(40, 200, 50, 25))
        self.pushButton_Heat_SW.setObjectName(_fromUtf8("pushButton__Heat_SW"))


        self.Lamp_Heat_Sorb_on = QtGui.QProgressBar(self.tab_ITC_Control)
        self.Lamp_Heat_Sorb_on.setGeometry(QtCore.QRect(10, 160, 21, 23))
        self.Lamp_Heat_Sorb_on.setMaximum(100)
        self.Lamp_Heat_Sorb_on.setProperty("value", 0)
        self.Lamp_Heat_Sorb_on.setAlignment(QtCore.Qt.AlignCenter)
        self.Lamp_Heat_Sorb_on.setTextVisible(False)
        self.Lamp_Heat_Sorb_on.setFormat(_fromUtf8(""))
        self.Lamp_Heat_Sorb_on.setObjectName(_fromUtf8("Lamp_Heat_Sorb"))
        self.pushButton_Heat_Sorb = QtGui.QPushButton(self.tab_ITC_Control)
        self.pushButton_Heat_Sorb.setGeometry(QtCore.QRect(40, 160, 50, 25))
        self.pushButton_Heat_Sorb.setObjectName(_fromUtf8("pushButton__Heat_Sorb"))













        self.Lamp_Valve_Open_ITC = QtGui.QProgressBar(self.tab_ITC_Control)
        self.Lamp_Valve_Open_ITC.setGeometry(QtCore.QRect(10, 290, 21, 23))
        self.Lamp_Valve_Open_ITC.setMaximum(1)
        self.Lamp_Valve_Open_ITC.setProperty("value", 0)
        self.Lamp_Valve_Open_ITC.setAlignment(QtCore.Qt.AlignCenter)
        self.Lamp_Valve_Open_ITC.setTextVisible(False)
        self.Lamp_Valve_Open_ITC.setFormat(_fromUtf8(""))
        self.Lamp_Valve_Open_ITC.setObjectName(_fromUtf8("Lamp_Valve_Open_ITC"))
        self.pushButton_Valve_open_ITC = QtGui.QPushButton(self.tab_ITC_Control)
        self.pushButton_Valve_open_ITC.setGeometry(QtCore.QRect(40, 290, 50, 25))
        self.pushButton_Valve_open_ITC.setObjectName(_fromUtf8("pushButton_Valve_open_ITC"))


        self.Lamp_Valve_Close_ITC = QtGui.QProgressBar(self.tab_ITC_Control)
        self.Lamp_Valve_Close_ITC.setGeometry(QtCore.QRect(310, 290, 21, 23))
        self.Lamp_Valve_Close_ITC.setMaximum(1)
        self.Lamp_Valve_Close_ITC.setProperty("value", 0)
        self.Lamp_Valve_Close_ITC.setAlignment(QtCore.Qt.AlignCenter)
        self.Lamp_Valve_Close_ITC.setTextVisible(False)
        self.Lamp_Valve_Close_ITC.setFormat(_fromUtf8(""))
        self.Lamp_Valve_Close_ITC.setObjectName(_fromUtf8("Lamp_Valve_Close_ITC"))
        self.pushButton_Valve_Close_ITC = QtGui.QPushButton(self.tab_ITC_Control)
        self.pushButton_Valve_Close_ITC.setGeometry(QtCore.QRect(250, 290, 50, 25))
        self.pushButton_Valve_Close_ITC.setObjectName(_fromUtf8("pushButton_Valve_Close_ITC"))



        self.tab_mmr_control = QtGui.QWidget()
        self.tab_mmr_control.setObjectName(_fromUtf8("tab_mmr_control"))
        self.tabWidget.addTab(self.tab_mmr_control, _fromUtf8(""))

        self.label_mmr_still = QtGui.QLabel(self.tab_mmr_control)
        self.label_mmr_still.setGeometry(QtCore.QRect(150, 100, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mmr_still.setFont(font)
        self.label_mmr_still.setObjectName(_fromUtf8("label_mmr_still"))
        self.pushButton_Valve_Close_mmr = QtGui.QPushButton(self.tab_mmr_control)
        self.pushButton_Valve_Close_mmr.setGeometry(QtCore.QRect(250, 290, 50, 25))
        self.pushButton_Valve_Close_mmr.setObjectName(_fromUtf8("pushButton_Valve_Close_mmr"))
        self.pushButton_Recon_On_mmr = QtGui.QPushButton(self.tab_mmr_control)
        self.pushButton_Recon_On_mmr.setGeometry(QtCore.QRect(40, 20, 50, 25))
        self.pushButton_Recon_On_mmr.setObjectName(_fromUtf8("pushButton_Recon_On_mmr"))
        self.lcdNumber_mmr_STILL = QtGui.QLCDNumber(self.tab_mmr_control)
        self.lcdNumber_mmr_STILL.setGeometry(QtCore.QRect(210, 90, 110, 40))
        self.lcdNumber_mmr_STILL.setSmallDecimalPoint(True)
        self.lcdNumber_mmr_STILL.setNumDigits(4)
        self.lcdNumber_mmr_STILL.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_mmr_STILL.setProperty("intValue", 0)
        self.lcdNumber_mmr_STILL.setObjectName(_fromUtf8("lcdNumber_16"))
        self.Lamp_Valve_Close_4 = QtGui.QProgressBar(self.tab_mmr_control)
        self.Lamp_Valve_Close_4.setGeometry(QtCore.QRect(310, 290, 21, 23))
        self.Lamp_Valve_Close_4.setMaximum(1)
        self.Lamp_Valve_Close_4.setProperty("value", 0)
        self.Lamp_Valve_Close_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Lamp_Valve_Close_4.setTextVisible(False)
        self.Lamp_Valve_Close_4.setFormat(_fromUtf8(""))
        self.Lamp_Valve_Close_4.setObjectName(_fromUtf8("Lamp_Valve_Close_4"))
        self.Lamp_Recon_On_4 = QtGui.QProgressBar(self.tab_mmr_control)
        self.Lamp_Recon_On_4.setGeometry(QtCore.QRect(10, 20, 21, 23))
        self.Lamp_Recon_On_4.setMaximum(1)
        self.Lamp_Recon_On_4.setProperty("value", 0)
        self.Lamp_Recon_On_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Lamp_Recon_On_4.setTextVisible(False)
        self.Lamp_Recon_On_4.setFormat(_fromUtf8(""))
        self.Lamp_Recon_On_4.setObjectName(_fromUtf8("Lamp_Recon_On_4"))
        self.label_Gauge_mmr_Heater = QtGui.QLabel(self.tab_mmr_control)
        self.label_Gauge_mmr_Heater.setGeometry(QtCore.QRect(150, 250, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Gauge_mmr_Heater.setFont(font)
        self.label_Gauge_mmr_Heater.setObjectName(_fromUtf8("label_Gauge_mmr_Heater"))
        self.lcdNumber_mmr_MIXING = QtGui.QLCDNumber(self.tab_mmr_control)
        self.lcdNumber_mmr_MIXING.setGeometry(QtCore.QRect(210, 130, 110, 40))
        self.lcdNumber_mmr_MIXING.setSmallDecimalPoint(True)
        self.lcdNumber_mmr_MIXING.setNumDigits(4)
        self.lcdNumber_mmr_MIXING.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_mmr_MIXING.setProperty("intValue", 0)
        self.lcdNumber_mmr_MIXING.setObjectName(_fromUtf8("lcdNumber_17"))
        self.lcdNumber_mmr_pt_1 = QtGui.QLCDNumber(self.tab_mmr_control)
        self.lcdNumber_mmr_pt_1.setGeometry(QtCore.QRect(210, 10, 110, 40))
        self.lcdNumber_mmr_pt_1.setSmallDecimalPoint(True)
        self.lcdNumber_mmr_pt_1.setNumDigits(4)
        self.lcdNumber_mmr_pt_1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_mmr_pt_1.setProperty("intValue", 0)
        self.lcdNumber_mmr_pt_1.setObjectName(_fromUtf8("lcdNumber_18"))
        self.label_mmr_pt_1 = QtGui.QLabel(self.tab_mmr_control)
        self.label_mmr_pt_1.setGeometry(QtCore.QRect(150, 20, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mmr_pt_1.setFont(font)
        self.label_mmr_pt_1.setObjectName(_fromUtf8("label_mmr_pt_1"))
        self.label_mmr_pt_2 = QtGui.QLabel(self.tab_mmr_control)
        self.label_mmr_pt_2.setGeometry(QtCore.QRect(150, 60, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mmr_pt_2.setFont(font)
        self.label_mmr_pt_2.setObjectName(_fromUtf8("label_mmr_pt_2"))
        self.label_mmr_mixing = QtGui.QLabel(self.tab_mmr_control)
        self.label_mmr_mixing.setGeometry(QtCore.QRect(150, 140, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mmr_mixing.setFont(font)
        self.label_mmr_mixing.setObjectName(_fromUtf8("label_mmr_mixing"))
        self.lcdNumber_mmr_pt_2 = QtGui.QLCDNumber(self.tab_mmr_control)
        self.lcdNumber_mmr_pt_2.setGeometry(QtCore.QRect(210, 50, 110, 40))
        self.lcdNumber_mmr_pt_2.setSmallDecimalPoint(True)
        self.lcdNumber_mmr_pt_2.setNumDigits(4)
        self.lcdNumber_mmr_pt_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_mmr_pt_2.setProperty("intValue", 0)
        self.lcdNumber_mmr_pt_2.setObjectName(_fromUtf8("lcdNumber_19"))
        self.pushButton_Valve_open_mmr = QtGui.QPushButton(self.tab_mmr_control)
        self.pushButton_Valve_open_mmr.setGeometry(QtCore.QRect(40, 290, 50, 25))
        self.pushButton_Valve_open_mmr.setObjectName(_fromUtf8("pushButton_Valve_open_mmr"))
        self.Lamp_Valve_Open_mmr = QtGui.QProgressBar(self.tab_mmr_control)
        self.Lamp_Valve_Open_mmr.setGeometry(QtCore.QRect(10, 290, 21, 23))
        self.Lamp_Valve_Open_mmr.setMaximum(1)
        self.Lamp_Valve_Open_mmr.setProperty("value", 0)
        self.Lamp_Valve_Open_mmr.setAlignment(QtCore.Qt.AlignCenter)
        self.Lamp_Valve_Open_mmr.setTextVisible(False)
        self.Lamp_Valve_Open_mmr.setFormat(_fromUtf8(""))
        self.Lamp_Valve_Open_mmr.setObjectName(_fromUtf8("Lamp_Valve_Open_mmr"))
        self.Gauge_Heat_power_mmr = QtGui.QProgressBar(self.tab_mmr_control)
        self.Gauge_Heat_power_mmr.setGeometry(QtCore.QRect(210, 250, 120, 20))
        self.Gauge_Heat_power_mmr.setMaximum(99)
        self.Gauge_Heat_power_mmr.setProperty("value", 0)
        self.Gauge_Heat_power_mmr.setObjectName(_fromUtf8("Gauge_Heat_power_mmr"))


        self.tab_Equip_Setup = QtGui.QWidget()
        self.tab_Equip_Setup.setObjectName(_fromUtf8("tab_Equip_Setup"))
        self.tabWidget.addTab(self.tab_Equip_Setup, _fromUtf8(""))

        self.checkBox_Vsd = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vsd.setGeometry(QtCore.QRect(5, 5, 15, 20))
        self.checkBox_Vsd.setText(_fromUtf8(""))
        self.checkBox_Vsd.setChecked(True)
        self.checkBox_Vsd.setAutoRepeat(True)
        self.checkBox_Vsd.setObjectName(_fromUtf8("checkBox_Vsd"))
        self.label_Vsd_yoko = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vsd_yoko.setGeometry(QtCore.QRect(30, 5, 46, 20))
        self.label_Vsd_yoko.setMouseTracking(False)
        self.label_Vsd_yoko.setObjectName(_fromUtf8("label_Vsd_yoko"))
        self.spinBox_GPIB_Vsd = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vsd.setGeometry(QtCore.QRect(80, 5, 42, 20))
        self.spinBox_GPIB_Vsd.setMinimum(1)
        self.spinBox_GPIB_Vsd.setMaximum(24)
        self.spinBox_GPIB_Vsd.setProperty("value", 3)
        self.spinBox_GPIB_Vsd.setObjectName(_fromUtf8("spinBox_GPIB_Vsd"))

        self.checkBox_Vg_1 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_1.setGeometry(QtCore.QRect(5, 30, 15, 20))
        self.checkBox_Vg_1.setText(_fromUtf8(""))
        self.checkBox_Vg_1.setChecked(True)
        self.checkBox_Vg_1.setAutoRepeat(True)
        self.checkBox_Vg_1.setObjectName(_fromUtf8("checkBox_Vg_1"))
        self.label_Vgate_1 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_1.setGeometry(QtCore.QRect(30, 30, 46, 20))
        self.label_Vgate_1.setMouseTracking(False)
        self.label_Vgate_1.setObjectName(_fromUtf8("label_Vgate_1"))
        self.spinBox_GPIB_Vg_1 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_1.setGeometry(QtCore.QRect(80, 30, 42, 20))
        self.spinBox_GPIB_Vg_1.setMinimum(1)
        self.spinBox_GPIB_Vg_1.setMaximum(24)
        self.spinBox_GPIB_Vg_1.setProperty("value", 2)
        self.spinBox_GPIB_Vg_1.setObjectName(_fromUtf8("spinBox_GPIB_Vg_1"))

        self.checkBox_Vg_2 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_2.setGeometry(QtCore.QRect(5, 55, 15, 20))
        self.checkBox_Vg_2.setText(_fromUtf8(""))
        self.checkBox_Vg_2.setAutoRepeat(True)
        self.checkBox_Vg_2.setObjectName(_fromUtf8("checkBox_Vg_2"))
        self.label_Vgate_2 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_2.setGeometry(QtCore.QRect(30, 55, 46, 20))
        self.label_Vgate_2.setMouseTracking(False)
        self.label_Vgate_2.setObjectName(_fromUtf8("label_Vgate_2"))
        self.spinBox_GPIB_Vg_2 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_2.setGeometry(QtCore.QRect(80, 55, 42, 20))
        self.spinBox_GPIB_Vg_2.setMinimum(1)
        self.spinBox_GPIB_Vg_2.setMaximum(24)
        self.spinBox_GPIB_Vg_2.setProperty("value", 4)
        self.spinBox_GPIB_Vg_2.setObjectName(_fromUtf8("spinBox_GPIB_Vg_2"))

        self.checkBox_Vg_3 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_3.setGeometry(QtCore.QRect(5, 80, 15, 20))
        self.checkBox_Vg_3.setText(_fromUtf8(""))
        self.checkBox_Vg_3.setAutoRepeat(True)
        self.checkBox_Vg_3.setObjectName(_fromUtf8("checkBox_Vg_3"))
        self.label_Vgate_3 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_3.setGeometry(QtCore.QRect(30, 80, 46, 20))
        self.label_Vgate_3.setMouseTracking(False)
        self.label_Vgate_3.setObjectName(_fromUtf8("label_Vgate_3"))
        self.spinBox_GPIB_Vg_3 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_3.setGeometry(QtCore.QRect(80, 80, 42, 20))
        self.spinBox_GPIB_Vg_3.setMinimum(1)
        self.spinBox_GPIB_Vg_3.setMaximum(24)
        self.spinBox_GPIB_Vg_3.setProperty("value", 5)
        self.spinBox_GPIB_Vg_3.setObjectName(_fromUtf8("spinBox_GPIB_Vg_3"))

        self.checkBox_Vg_4 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_4.setGeometry(QtCore.QRect(5, 105, 15, 20))
        self.checkBox_Vg_4.setText(_fromUtf8(""))
        self.checkBox_Vg_4.setAutoRepeat(True)
        self.checkBox_Vg_4.setObjectName(_fromUtf8("checkBox_Vg_4"))
        self.label_Vgate_4 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_4.setGeometry(QtCore.QRect(30, 105, 46, 20))
        self.label_Vgate_4.setMouseTracking(False)
        self.label_Vgate_4.setObjectName(_fromUtf8("label_Vgate_4"))
        self.spinBox_GPIB_Vg_4 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_4.setGeometry(QtCore.QRect(80, 105, 42, 20))
        self.spinBox_GPIB_Vg_4.setMinimum(1)
        self.spinBox_GPIB_Vg_4.setMaximum(24)
        self.spinBox_GPIB_Vg_4.setProperty("value", 6)
        self.spinBox_GPIB_Vg_4.setObjectName(_fromUtf8("spinBox_GPIB_Vg_4"))

        self.checkBox_Vg_5 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_5.setGeometry(QtCore.QRect(5, 130, 15, 20))
        self.checkBox_Vg_5.setText(_fromUtf8(""))
        self.checkBox_Vg_5.setAutoRepeat(True)
        self.checkBox_Vg_5.setObjectName(_fromUtf8("checkBox_Vg_5"))
        self.label_Vgate_5 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_5.setGeometry(QtCore.QRect(30, 130, 46, 20))
        self.label_Vgate_5.setMouseTracking(False)
        self.label_Vgate_5.setObjectName(_fromUtf8("label_Vgate_5"))
        self.spinBox_GPIB_Vg_5 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_5.setGeometry(QtCore.QRect(80, 130, 42, 20))
        self.spinBox_GPIB_Vg_5.setMinimum(1)
        self.spinBox_GPIB_Vg_5.setMaximum(24)
        self.spinBox_GPIB_Vg_5.setProperty("value", 7)
        self.spinBox_GPIB_Vg_5.setObjectName(_fromUtf8("spinBox_GPIB_Vg_5"))

        self.checkBox_Vg_6 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_6.setGeometry(QtCore.QRect(5, 155, 15, 20))
        self.checkBox_Vg_6.setText(_fromUtf8(""))
        self.checkBox_Vg_6.setAutoRepeat(True)
        self.checkBox_Vg_6.setObjectName(_fromUtf8("checkBox_Vg_6"))
        self.label_Vgate_6 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_6.setGeometry(QtCore.QRect(30, 155, 46, 20))
        self.label_Vgate_6.setMouseTracking(False)
        self.label_Vgate_6.setObjectName(_fromUtf8("label_Vgate_6"))
        self.spinBox_GPIB_Vg_6 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_6.setGeometry(QtCore.QRect(80, 155, 42, 20))
        self.spinBox_GPIB_Vg_6.setMinimum(1)
        self.spinBox_GPIB_Vg_6.setMaximum(24)
        self.spinBox_GPIB_Vg_6.setProperty("value", 8)
        self.spinBox_GPIB_Vg_6.setObjectName(_fromUtf8("spinBox_GPIB_Vg_6"))

        self.checkBox_Vg_7 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_7.setGeometry(QtCore.QRect(5, 180, 15, 20))
        self.checkBox_Vg_7.setText(_fromUtf8(""))
        self.checkBox_Vg_7.setAutoRepeat(True)
        self.checkBox_Vg_7.setObjectName(_fromUtf8("checkBox_Vg_7"))
        self.label_Vgate_7 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_7.setGeometry(QtCore.QRect(30, 180, 46, 20))
        self.label_Vgate_7.setMouseTracking(False)
        self.label_Vgate_7.setObjectName(_fromUtf8("label_Vgate_7"))
        self.spinBox_GPIB_Vg_7 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_7.setGeometry(QtCore.QRect(80, 180, 42, 20))
        self.spinBox_GPIB_Vg_7.setMinimum(1)
        self.spinBox_GPIB_Vg_7.setMaximum(24)
        self.spinBox_GPIB_Vg_7.setProperty("value", 9)
        self.spinBox_GPIB_Vg_7.setObjectName(_fromUtf8("spinBox_GPIB_Vg_7"))

        self.checkBox_Vg_8 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_8.setGeometry(QtCore.QRect(5, 205, 15, 20))
        self.checkBox_Vg_8.setText(_fromUtf8(""))
        self.checkBox_Vg_8.setAutoRepeat(True)
        self.checkBox_Vg_8.setObjectName(_fromUtf8("checkBox_Vg_8"))
        self.label_Vgate_8 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_8.setGeometry(QtCore.QRect(30, 205, 46, 20))
        self.label_Vgate_8.setMouseTracking(False)
        self.label_Vgate_8.setObjectName(_fromUtf8("label_Vgate_8"))
        self.spinBox_GPIB_Vg_8 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_8.setGeometry(QtCore.QRect(80, 205, 42, 20))
        self.spinBox_GPIB_Vg_8.setMinimum(1)
        self.spinBox_GPIB_Vg_8.setMaximum(24)
        self.spinBox_GPIB_Vg_8.setProperty("value", 10)
        self.spinBox_GPIB_Vg_8.setObjectName(_fromUtf8("spinBox_GPIB_Vg_8"))

        self.checkBox_Vg_9 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_9.setGeometry(QtCore.QRect(5, 230, 15, 20))
        self.checkBox_Vg_9.setText(_fromUtf8(""))
        self.checkBox_Vg_9.setAutoRepeat(True)
        self.checkBox_Vg_9.setObjectName(_fromUtf8("checkBox_Vg_9"))
        self.label_Vgate_9 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_9.setGeometry(QtCore.QRect(30, 230, 46, 20))
        self.label_Vgate_9.setMouseTracking(False)
        self.label_Vgate_9.setObjectName(_fromUtf8("label_Vgate_9"))
        self.spinBox_GPIB_Vg_9 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_9.setGeometry(QtCore.QRect(80, 230, 42, 20))
        self.spinBox_GPIB_Vg_9.setMinimum(1)
        self.spinBox_GPIB_Vg_9.setMaximum(24)
        self.spinBox_GPIB_Vg_9.setProperty("value", 11)
        self.spinBox_GPIB_Vg_9.setObjectName(_fromUtf8("spinBox_GPIB_Vg_9"))

        self.checkBox_Vg_10 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_10.setGeometry(QtCore.QRect(5, 255, 15, 20))
        self.checkBox_Vg_10.setText(_fromUtf8(""))
        self.checkBox_Vg_10.setAutoRepeat(True)
        self.checkBox_Vg_10.setObjectName(_fromUtf8("checkBox_Vg_10"))
        self.label_Vgate_10 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_10.setGeometry(QtCore.QRect(30, 255, 46, 20))
        self.label_Vgate_10.setMouseTracking(False)
        self.label_Vgate_10.setObjectName(_fromUtf8("label_Vgate_10"))
        self.spinBox_GPIB_Vg_10 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_10.setGeometry(QtCore.QRect(80, 255, 42, 20))
        self.spinBox_GPIB_Vg_10.setMinimum(1)
        self.spinBox_GPIB_Vg_10.setMaximum(24)
        self.spinBox_GPIB_Vg_10.setProperty("value", 12)
        self.spinBox_GPIB_Vg_10.setObjectName(_fromUtf8("spinBox_GPIB_Vg_10"))

        self.checkBox_Vg_11 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_11.setGeometry(QtCore.QRect(5, 280, 15, 20))
        self.checkBox_Vg_11.setText(_fromUtf8(""))
        self.checkBox_Vg_11.setAutoRepeat(True)
        self.checkBox_Vg_11.setObjectName(_fromUtf8("checkBox_Vg_11"))
        self.label_Vgate_11 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_11.setGeometry(QtCore.QRect(30, 280, 46, 20))
        self.label_Vgate_11.setMouseTracking(False)
        self.label_Vgate_11.setObjectName(_fromUtf8("label_Vgate_11"))
        self.spinBox_GPIB_Vg_11 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_11.setGeometry(QtCore.QRect(80, 280, 42, 20))
        self.spinBox_GPIB_Vg_11.setMinimum(1)
        self.spinBox_GPIB_Vg_11.setMaximum(24)
        self.spinBox_GPIB_Vg_11.setProperty("value", 14)
        self.spinBox_GPIB_Vg_11.setObjectName(_fromUtf8("spinBox_GPIB_Vg_11"))

        self.checkBox_Vg_12 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Vg_12.setGeometry(QtCore.QRect(5, 305, 15, 20))
        self.checkBox_Vg_12.setText(_fromUtf8(""))
        self.checkBox_Vg_12.setAutoRepeat(True)
        self.checkBox_Vg_12.setObjectName(_fromUtf8("checkBox_Vg_12"))
        self.label_Vgate_12 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Vgate_12.setGeometry(QtCore.QRect(30, 305, 46, 20))
        self.label_Vgate_12.setMouseTracking(False)
        self.label_Vgate_12.setObjectName(_fromUtf8("label_Vgate_12"))
        self.spinBox_GPIB_Vg_12 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Vg_12.setGeometry(QtCore.QRect(80, 305, 42, 20))
        self.spinBox_GPIB_Vg_12.setMinimum(1)
        self.spinBox_GPIB_Vg_12.setMaximum(24)
        self.spinBox_GPIB_Vg_12.setProperty("value", 15)
        self.spinBox_GPIB_Vg_12.setObjectName(_fromUtf8("spinBox_GPIB_Vg_12"))

        self.checkBox_ITC_1 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_ITC_1.setGeometry(QtCore.QRect(150, 5, 15, 20))
        self.checkBox_ITC_1.setText(_fromUtf8(""))
        self.checkBox_ITC_1.setChecked(True)
        self.checkBox_ITC_1.setAutoRepeat(True)
        self.checkBox_ITC_1.setObjectName(_fromUtf8("checkBox_ITC_1"))
        self.label_ITC_1 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_ITC_1.setGeometry(QtCore.QRect(175, 5, 46, 20))
        self.label_ITC_1.setMouseTracking(False)
        self.label_ITC_1.setObjectName(_fromUtf8("label_ITC_1"))
        self.spinBox_GPIB_ITC_1 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_ITC_1.setGeometry(QtCore.QRect(225, 5, 42, 20))
        self.spinBox_GPIB_ITC_1.setMinimum(1)
        self.spinBox_GPIB_ITC_1.setMaximum(24)
        self.spinBox_GPIB_ITC_1.setProperty("value", 23)
        self.spinBox_GPIB_ITC_1.setObjectName(_fromUtf8("spinBox_GPIB_ITC_1"))

        self.checkBox_ITC_2 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_ITC_2.setGeometry(QtCore.QRect(150, 30, 15, 20))
        self.checkBox_ITC_2.setText(_fromUtf8(""))
        self.checkBox_ITC_2.setChecked(True)
        self.checkBox_ITC_2.setAutoRepeat(True)
        self.checkBox_ITC_2.setObjectName(_fromUtf8("checkBox_ITC_2"))
        self.label_ITC_2 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_ITC_2.setGeometry(QtCore.QRect(175, 30, 46, 20))
        self.label_ITC_2.setMouseTracking(False)
        self.label_ITC_2.setObjectName(_fromUtf8("label_ITC_2"))
        self.spinBox_GPIB_ITC_2 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_ITC_2.setGeometry(QtCore.QRect(225, 30, 42, 20))
        self.spinBox_GPIB_ITC_2.setMinimum(1)
        self.spinBox_GPIB_ITC_2.setMaximum(24)
        self.spinBox_GPIB_ITC_2.setProperty("value", 24)
        self.spinBox_GPIB_ITC_2.setObjectName(_fromUtf8("spinBox_GPIB_ITC_2"))


        self.checkBox_lockin_7265 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_lockin_7265.setGeometry(QtCore.QRect(150, 55, 15, 20))
        self.checkBox_lockin_7265.setText(_fromUtf8(""))
        self.checkBox_lockin_7265.setChecked(True)
        self.checkBox_lockin_7265.setAutoRepeat(True)
        self.checkBox_lockin_7265.setObjectName(_fromUtf8("checkBox_lockin_7265"))
        self.label_lockin_7265 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_lockin_7265.setGeometry(QtCore.QRect(175, 55, 46, 20))
        self.label_lockin_7265.setMouseTracking(False)
        self.label_lockin_7265.setObjectName(_fromUtf8("label_lockin_7265"))
        self.spinBox_GPIB_lockin_7265 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_lockin_7265.setGeometry(QtCore.QRect(225, 55, 42, 20))
        self.spinBox_GPIB_lockin_7265.setMinimum(1)
        self.spinBox_GPIB_lockin_7265.setMaximum(24)
        self.spinBox_GPIB_lockin_7265.setProperty("value", 13)
        self.spinBox_GPIB_lockin_7265.setObjectName(_fromUtf8("spinBox_GPIB_lockin_7265"))

        self.checkBox_awg_33210 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_awg_33210.setGeometry(QtCore.QRect(150, 80, 15, 20))
        self.checkBox_awg_33210.setText(_fromUtf8(""))
        self.checkBox_awg_33210.setChecked(False)
        self.checkBox_awg_33210.setAutoRepeat(True)
        self.checkBox_awg_33210.setObjectName(_fromUtf8("checkBox_awg_33210"))
        self.label_awg_33210 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_awg_33210.setGeometry(QtCore.QRect(175, 80, 46, 20))
        self.label_awg_33210.setMouseTracking(False)
        self.label_awg_33210.setObjectName(_fromUtf8("label_awg_33210"))
        self.spinBox_GPIB_awg_33210 = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_awg_33210.setGeometry(QtCore.QRect(225, 80, 42, 20))
        self.spinBox_GPIB_awg_33210.setMinimum(1)
        self.spinBox_GPIB_awg_33210.setMaximum(24)
        self.spinBox_GPIB_awg_33210.setProperty("value", 13)
        self.spinBox_GPIB_awg_33210.setObjectName(_fromUtf8("spinBox_GPIB_awg_33210"))

        self.checkBox_Magnet = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Magnet.setGeometry(QtCore.QRect(150, 105, 15, 20))
        self.checkBox_Magnet.setText(_fromUtf8(""))
        self.checkBox_Magnet.setChecked(False)
        self.checkBox_Magnet.setAutoRepeat(True)
        self.checkBox_Magnet.setObjectName(_fromUtf8("checkBox_Magnet"))
        self.label_Magnet = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Magnet.setGeometry(QtCore.QRect(175, 105, 46, 20))
        self.label_Magnet.setMouseTracking(False)
        self.label_Magnet.setObjectName(_fromUtf8("label_Magnet"))
        self.spinBox_GPIB_Magnet = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Magnet.setGeometry(QtCore.QRect(225, 105, 42, 20))
        self.spinBox_GPIB_Magnet.setMinimum(1)
        self.spinBox_GPIB_Magnet.setMaximum(24)
        self.spinBox_GPIB_Magnet.setProperty("value", 13)
        self.spinBox_GPIB_Magnet.setObjectName(_fromUtf8("spinBox_GPIB_Magnet"))

        self.checkBox_adlink9826 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_adlink9826.setGeometry(QtCore.QRect(150, 130, 15, 20))
        self.checkBox_adlink9826.setText(_fromUtf8(""))
        self.checkBox_adlink9826.setChecked(True)
        self.checkBox_adlink9826.setAutoRepeat(True)
        self.checkBox_adlink9826.setObjectName(_fromUtf8("checkBox_adlink9826"))
        self.label_adlink9826 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_adlink9826.setGeometry(QtCore.QRect(175, 130, 46, 20))
        self.label_adlink9826.setMouseTracking(False)
        self.label_adlink9826.setObjectName(_fromUtf8("label_adlink9826"))

        self.checkBox_Toptica = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_Toptica.setGeometry(QtCore.QRect(150, 155, 15, 20))
        self.checkBox_Toptica.setText(_fromUtf8(""))
        self.checkBox_Toptica.setChecked(False)
        self.checkBox_Toptica.setAutoRepeat(True)
        self.checkBox_Toptica.setObjectName(_fromUtf8("checkBox_Toptica"))
        self.spinBox_GPIB_Toptica = QtGui.QSpinBox(self.tab_Equip_Setup)
        self.spinBox_GPIB_Toptica.setGeometry(QtCore.QRect(205, 155, 42, 20))
        self.spinBox_GPIB_Toptica.setMinimum(1)
        self.spinBox_GPIB_Toptica.setMaximum(12)
        self.spinBox_GPIB_Toptica.setProperty("value", 8)
        self.spinBox_GPIB_Toptica.setObjectName(_fromUtf8("spinBox_GPIB_Toptica"))
        self.label_Toptica = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_Toptica.setGeometry(QtCore.QRect(175, 155, 46, 20))
        self.label_Toptica.setMouseTracking(False)
        self.label_Toptica.setObjectName(_fromUtf8("label_Toptica"))

        self.checkBox_mmr3_1 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_mmr3_1.setGeometry(QtCore.QRect(150, 255, 15, 20))
        self.checkBox_mmr3_1.setText(_fromUtf8(""))
        self.checkBox_mmr3_1.setChecked(False)
        self.checkBox_mmr3_1.setAutoRepeat(True)
        self.checkBox_mmr3_1.setObjectName(_fromUtf8("checkBox_mmr3_1"))
        self.label_mmr3_1 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_mmr3_1.setGeometry(QtCore.QRect(175, 255, 45, 20))
        self.label_mmr3_1.setMouseTracking(False)
        self.label_mmr3_1.setObjectName(_fromUtf8("label_mmr3_1"))
        self.textEdit_mmr3_1_address = QtGui.QTextEdit(self.tab_Equip_Setup)
        self.textEdit_mmr3_1_address.setGeometry(QtCore.QRect(220, 255, 111, 20))
        self.textEdit_mmr3_1_address.setObjectName(_fromUtf8("textEdit_mmr3_1_address"))


        self.checkBox_mmr3_2 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_mmr3_2.setGeometry(QtCore.QRect(150, 280, 15, 20))
        self.checkBox_mmr3_2.setText(_fromUtf8(""))
        self.checkBox_mmr3_2.setChecked(False)
        self.checkBox_mmr3_2.setAutoRepeat(True)
        self.checkBox_mmr3_2.setObjectName(_fromUtf8("checkBox_mmr3_2"))
        self.label_mmr3_2 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_mmr3_2.setGeometry(QtCore.QRect(175, 280, 45, 20))
        self.label_mmr3_2.setMouseTracking(False)
        self.label_mmr3_2.setObjectName(_fromUtf8("label_mmr3_2"))
        self.textEdit_mmr3_2_address = QtGui.QTextEdit(self.tab_Equip_Setup)
        self.textEdit_mmr3_2_address.setGeometry(QtCore.QRect(220, 280, 111, 20))
        self.textEdit_mmr3_2_address.setObjectName(_fromUtf8("textEdit_mmr3_2_address"))

        self.checkBox_mmr3_3 = QtGui.QCheckBox(self.tab_Equip_Setup)
        self.checkBox_mmr3_3.setGeometry(QtCore.QRect(150, 305, 15, 20))
        self.checkBox_mmr3_3.setText(_fromUtf8(""))
        self.checkBox_mmr3_3.setChecked(False)
        self.checkBox_mmr3_3.setAutoRepeat(True)
        self.checkBox_mmr3_3.setObjectName(_fromUtf8("checkBox_mmr3_3"))
        self.label_mmr3_3 = QtGui.QLabel(self.tab_Equip_Setup)
        self.label_mmr3_3.setGeometry(QtCore.QRect(175, 305, 45, 20))
        self.label_mmr3_3.setMouseTracking(False)
        self.label_mmr3_3.setObjectName(_fromUtf8("label_mmr3_3"))
        self.textEdit_mmr3_3_address = QtGui.QTextEdit(self.tab_Equip_Setup)
        self.textEdit_mmr3_3_address.setGeometry(QtCore.QRect(220, 305, 111, 20))
        self.textEdit_mmr3_3_address.setObjectName(_fromUtf8("textEdit_mmr3_3_address"))






        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1228, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Dat = QtGui.QAction(MainWindow)
        self.actionImport_Dat.setObjectName(_fromUtf8("actionImport_Dat"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionQuit.setStatusTip('Leave The App')

        self.menuFile.addAction(self.actionImport_Dat)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())


        #QtCore.QObject.connect(self.pushButton_Profile_fig_1, SIGNAL("clicked()"), self.Profile_fig_1_btn_clicked)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_PT2.setText(_translate("MainWindow", "PT 2", None))
        self.label_ITC_He3Low.setText(_translate("MainWindow", "He3Low", None))
        self.label_HeatSW.setText(_translate("MainWindow", "Heat SW", None))
        self.label_He3High.setText(_translate("MainWindow", "He3High", None))
        self.label_ITC_Sorb.setText(_translate("MainWindow", "Sorb", None))
        self.label_Gauge_sorb_ITC.setText(_translate("MainWindow", "Sorb", None))
        self.label_Gauge_Heatsw_ITC.setText(_translate("MainWindow", "Heat SW", None))
        self.pushButton_Valve_open_ITC.setText(_translate("MainWindow", "V Open", None))
        self.pushButton_Valve_Close_ITC.setText(_translate("MainWindow", "V Close", None))
        self.pushButton_Recon_On_ITC.setText(_translate("MainWindow", "Auto-Recon", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ITC_Control), _translate("MainWindow", "ITC Control", None))
        self.label_mmr_still.setText(_translate("MainWindow", "STILL", None))
        self.pushButton_Valve_Close_mmr.setText(_translate("MainWindow", "V Close", None))
        self.pushButton_Recon_On_mmr.setText(_translate("MainWindow", "Recon", None))
        self.label_Gauge_mmr_Heater.setText(_translate("MainWindow", "Heater", None))
        self.label_mmr_pt_1.setText(_translate("MainWindow", "PT1", None))
        self.label_mmr_pt_2.setText(_translate("MainWindow", "PT2", None))
        self.label_mmr_mixing.setText(_translate("MainWindow", "MIXING", None))
        self.pushButton_Valve_open_mmr.setText(_translate("MainWindow", "V Open", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mmr_control), _translate("MainWindow", "MMR Control", None))
        self.label_Vsd_yoko.setText(_translate("MainWindow", "Vsd", None))
        self.label_Vgate_1.setText(_translate("MainWindow", "Vg1", None))
        self.label_Vgate_2.setText(_translate("MainWindow", "Vg2", None))
        self.label_Vgate_3.setText(_translate("MainWindow", "Vg3", None))
        self.label_Vgate_4.setText(_translate("MainWindow", "Vg4", None))
        self.label_Vgate_5.setText(_translate("MainWindow", "Vg5", None))
        self.label_Vgate_6.setText(_translate("MainWindow", "Vg6", None))
        self.label_Vgate_7.setText(_translate("MainWindow", "Vg7", None))
        self.label_Vgate_8.setText(_translate("MainWindow", "Vg8", None))
        self.label_Vgate_9.setText(_translate("MainWindow", "Vg9", None))
        self.label_Vgate_10.setText(_translate("MainWindow", "Vg10", None))
        self.label_Vgate_11.setText(_translate("MainWindow", "Vg11", None))
        self.label_Vgate_12.setText(_translate("MainWindow", "Vg12", None))
        self.label_ITC_2.setText(_translate("MainWindow", "ITC2", None))
        self.label_ITC_1.setText(_translate("MainWindow", "ITC1", None))
        self.label_lockin_7265.setText(_translate("MainWindow", "7265", None))
        self.label_adlink9826.setText(_translate("MainWindow", "AD9826", None))
        self.label_Toptica.setText(_translate("MainWindow", "Toptica", None))
        self.label_mmr3_1.setText(_translate("MainWindow", "mmr3_1", None))
        self.label_mmr3_2.setText(_translate("MainWindow", "mmr3_2", None))
        self.label_mmr3_3.setText(_translate("MainWindow", "mmr3_3", None))
        self.label_awg_33210.setText(_translate("MainWindow", "A33210", None))
        self.label_Magnet.setText(_translate("MainWindow", "Magnet", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Equip_Setup), _translate("MainWindow", "Equip Setup", None))
        self.label_X_axis.setText(_translate("MainWindow", "X-axis", None))
        self.label_Y_axis.setText(_translate("MainWindow", "Y-axis", None))
        self.label_Z_axis.setText(_translate("MainWindow", "Z-axis", None))
        self.label_Measure_Noise.setText(_translate("MainWindow", "Noise", None))
        self.label_Measure_lockin.setText(_translate("MainWindow", "lockin", None))

        self.label_Start.setText(_translate("MainWindow", "Start", None))
        self.label_Stop.setText(_translate("MainWindow", "Stop", None))
        self.label_Step.setText(_translate("MainWindow", "Step", None))
        self.label_Datapoint.setText(_translate("MainWindow", "Data #", None))
        self.label_r_axis.setText(_translate("MainWindow", "R-axis", None))
        self.label_repeat.setText(_translate("MainWindow", "Repeat", None))
        self.label_wait_time.setText(_translate("MainWindow", "W.time", None))
        self.radioButton_preset_1.setText(_translate("MainWindow", "Preset ITC", None))
        self.radioButton_2.setText(_translate("MainWindow", "Preset MMR", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_Figure_Setup), _translate("MainWindow", "Figure Setup", None))
        self.label_ADLINK_save.setText(_translate("MainWindow", "Save", None))
        self.label_ADLINK_avgnum.setText(_translate("MainWindow", "# Avg", None))
        self.label_ADLINK_9826.setText(_translate("MainWindow", "ADLINK 9826", None))
        self.label_Stop_2.setText(_translate("MainWindow", "Stop", None))
        self.label_Start_2.setText(_translate("MainWindow", "Start", None))
        self.label_Volt_of_Amp_A.setText(_translate("MainWindow", "Volt Amp A", None))
        self.label_Volt_of_Amp_B.setText(_translate("MainWindow", "Volt Amp B", None))
        self.label_Volt_of_Amp_A_2.setText(_translate("MainWindow", "Bat. Charge", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_Parameters_2), _translate("MainWindow", "Parameters", None))
        self.pushButton_run.setText(_translate("MainWindow", "Run", None))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause", None))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionImport_Dat.setText(_translate("MainWindow", "Import Dat", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+C", None))



